### ISSUE TITLE
Creación de documentos ATAM y QAW

### ISSUE THREAD

**Issue by JuanDuquee** [camilohreina/task-manager-app#27]

**Comment by dqvdd** [comment]
Ya se realizó la documentación

[Evaluación de Arquitectura.docx](https://github.com/camilohreina/task-manager-app/files/12841961/Evaluacion.de.Arquitectura.docx)
[C4 Diagram - Task Manager.pdf](https://github.com/camilohreina/task-manager-app/files/12841962/C4.Diagram.-.Task.Manager.pdf)
